version: '3'

services:
  app:
    container_name: app
    build: ./docker
    ports:
        - 8080:8080
    privileged: true
    volumes:
        - ./app:/usr/src/app
    tty: true
    stdin_open: true
    command: /bin/sh
